#!/bin/bash

path="/home/garett/pictures/screenshots/$(date +%Y)/$(date +%B)"
filename=$(date +"%Y-%m-%d-%H:%M").png



if [[ -d $path ]]; then
	maim -s $path/$filename || exit 1
	cat $path/$filename | xclip -selection clipboard -t image/png
	notify-send -i "/usr/share/icons/Chicago95/devices/48/camera-photo.png" "screenshot taken" "$filename copied to clipboard!"
else
	mkdir -p $path
	maim -s $path/$filename || exit 1
	cat $path/$filename | xclip -selection clipboard -t image/png
	notify-send -i "/usr/share/icons/Chicago95/devices/48/camera-photo.png" "first screenshot of the month!" "$filename copied to clipboard!"
fi
